package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.Account;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	Account selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Account
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	int updateByPrimaryKey(Account record);
	
	List<Account> selectAll();
	Account selectByname(String name);
	//Account selectByUserid(String userid);
}