package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.AccountRole;

public interface AccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    int insert(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    int insertSelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    AccountRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    int updateByPrimaryKeySelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountRole
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    int updateByPrimaryKey(AccountRole record);
    List<AccountRole> selectAll();
    AccountRole selectByName(String username);
}