package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.AdminUser;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    int deleteByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    AdminUser selectByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminUser
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    int updateByPrimaryKey(AdminUser record);
    List<AdminUser> selectAll();
}