package com.shuodao.hrms.db.mapper;

import com.shuodao.hrms.db.entity.CertificateRecord;

public interface CertificateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    int insert(CertificateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    int insertSelective(CertificateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    CertificateRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    int updateByPrimaryKeySelective(CertificateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateRecord
     *
     * @mbg.generated Sun Aug 20 00:04:52 CST 2017
     */
    int updateByPrimaryKey(CertificateRecord record);
}