package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.DepartmentLevelInfo;

public interface DepartmentLevelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    int insert(DepartmentLevelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    int insertSelective(DepartmentLevelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    DepartmentLevelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    int updateByPrimaryKeySelective(DepartmentLevelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DepartmentLevelInfo
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    int updateByPrimaryKey(DepartmentLevelInfo record);
    List<DepartmentLevelInfo> selectAll();
    //DepartmentLevelInfo selectByName(String name);
    int deleteDeptlevelAndDeptInfo(Integer id);
    int deleteById(Integer id);
}