package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.shuodao.hrms.db.entity.Detail;

public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    int insertSelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    Detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    int updateByPrimaryKeySelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Detail
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    int updateByPrimaryKey(Detail record);
    List<Detail> selectAll();
    List<Detail> selectDetailListByMultiCondition(Map<String,Object> params,RowBounds rowbounds);
    int selectDetailListCountByMultiCondition(Map<String,Object> params);
    List<Detail> selectByKeyword(@Param("keyword")String keyword);
    Detail selectByEid(String eid);
}