package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.shuodao.hrms.db.entity.employee;

public interface employeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    int insert(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    int insertSelective(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    int updateByPrimaryKeySelective(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    int updateByPrimaryKey(employee record);
    List<employee> selectAll();
   int selectEmployeeListCountByMultiCondition(Map<String,Object> params);
   employee selectByEmployeeEdu (String education);
   employee selectByEmployeeDept(String department);
   employee selectByEmployeeRstatus(String rstatus);
   List<employee> selectEmployeeListByMultiCondition(Map<String,Object> params,RowBounds rowBounds);
   List<employee> selectByKeyword(@Param("keyword")String keyword);
   employee selectByName(String name);
   int selectEmployeeBaseListCountByMultiCondition(Map<String,Object> params);
   List<employee> selectEmployeeBaseListByMultiCondition(Map<String,Object> params,RowBounds rowBounds);
   List<employee> selectByAge(Map<String,Object> params);
   employee selectByUserid(String userid);
}