package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.InstitutionInfo;

public interface InstitutionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    int insert(InstitutionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    int insertSelective(InstitutionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    InstitutionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    int updateByPrimaryKeySelective(InstitutionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstitutionInfo
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    int updateByPrimaryKey(InstitutionInfo record);
    List<InstitutionInfo> selectAll();
}