package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Permission
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    int updateByPrimaryKey(Permission record);
    List<Permission> selectAll();
}