package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

import com.shuodao.hrms.db.entity.RewardsAndPunishments;

public interface RewardsAndPunishmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    int insert(RewardsAndPunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    int insertSelective(RewardsAndPunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    RewardsAndPunishments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    int updateByPrimaryKeySelective(RewardsAndPunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RewardsAndPunishments
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    int updateByPrimaryKey(RewardsAndPunishments record);
    List<RewardsAndPunishments> selectRewardsAndPunishmentsListByConditionMultiply(Map<String,Object> params,RowBounds rowBounds);
    int selectRewardsAndPunishmentsListCountByConditionMultiply(Map<String,Object> params);
    List<RewardsAndPunishments> selectAll();
    List<RewardsAndPunishments> selectByRewardsuser(String user);
}