package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.RoleInfo;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    RoleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    int updateByPrimaryKey(RoleInfo record);
    List<RoleInfo> selectAll();
    RoleInfo selectByName(String name);
}