package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.shuodao.hrms.db.entity.TitleRecord;

public interface TitleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    int insert(TitleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    int insertSelective(TitleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    TitleRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    int updateByPrimaryKeySelective(TitleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TitleRecord
     *
     * @mbg.generated Sat Oct 28 21:30:32 CST 2017
     */
    int updateByPrimaryKey(TitleRecord record);
    List<TitleRecord> selectAll();
    List<TitleRecord> selectByKeyWord(@Param("keyword") String keyword);
    TitleRecord selectByEmployeeid(String eid);
    int selectTitleRecordListByKeyword(Map<String,Object> params);
    
}