package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import com.shuodao.hrms.db.entity.trainigRecord;

public interface trainigRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    int insert(trainigRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    int insertSelective(trainigRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    trainigRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    int updateByPrimaryKeySelective(trainigRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainingRecord
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    int updateByPrimaryKey(trainigRecord record);
    
    List<trainigRecord> selectAll();
    List<trainigRecord> selectByEid(Map<String,Object> param);
    List<trainigRecord> selectByCategory(Map<String,Object> param);
    int selectCountByName(Map<String,Object> param);
    int getCount();
}