package com.shuodao.hrms.db.mapper;

import java.util.List;

import com.shuodao.hrms.db.entity.TrainCategory;

public interface TrainCategoryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	int insert(TrainCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	int insertSelective(TrainCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	TrainCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	int updateByPrimaryKeySelective(TrainCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TrainCategory
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	int updateByPrimaryKey(TrainCategory record);

	List<TrainCategory> selectAll();
}