package com.shuodao.hrms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.shuodao.hrms.db.entity.TransferInformation;

public interface TransferInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    int insert(TransferInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    int insertSelective(TransferInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    TransferInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    int updateByPrimaryKeySelective(TransferInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TransferInformation
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    int updateByPrimaryKey(TransferInformation record);
    List<TransferInformation> selectAll();
    List<TransferInformation> selectTransferInformationListByMultiCondition(Map<String,Object> params,RowBounds rowBounds);
    int selectTransferInformationCountByMultiCondition(Map<String,Object>params);
    List<TransferInformation> selectByKeyword(@Param("keyword") String keyword);
}