package com.shuodao.hrms.db.entity;

public class AccountRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountRole.id
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountRole.username
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountRole.rolename
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountRole.id
     *
     * @return the value of AccountRole.id
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountRole.id
     *
     * @param id the value for AccountRole.id
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountRole.username
     *
     * @return the value of AccountRole.username
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountRole.username
     *
     * @param username the value for AccountRole.username
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountRole.rolename
     *
     * @return the value of AccountRole.rolename
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountRole.rolename
     *
     * @param rolename the value for AccountRole.rolename
     *
     * @mbg.generated Fri Sep 22 00:15:59 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}