package com.shuodao.hrms.db.entity;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Account.id
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Account.username
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Account.pwd
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Account.roleid
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Account.id
	 * @return  the value of Account.id
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Account.id
	 * @param id  the value for Account.id
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Account.username
	 * @return  the value of Account.username
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Account.username
	 * @param username  the value for Account.username
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Account.pwd
	 * @return  the value of Account.pwd
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Account.pwd
	 * @param pwd  the value for Account.pwd
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Account.roleid
	 * @return  the value of Account.roleid
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Account.status
	 * @param status  the value for Account.status
	 * @mbg.generated  Sat Sep 02 16:26:00 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}