package com.shuodao.hrms.db.entity;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminUser.admin_id
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminUser.nick
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminUser.password
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminUser.role
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminUser.admin_id
     *
     * @return the value of AdminUser.admin_id
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminUser.admin_id
     *
     * @param adminId the value for AdminUser.admin_id
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminUser.nick
     *
     * @return the value of AdminUser.nick
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminUser.nick
     *
     * @param nick the value for AdminUser.nick
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminUser.password
     *
     * @return the value of AdminUser.password
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminUser.password
     *
     * @param password the value for AdminUser.password
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminUser.role
     *
     * @return the value of AdminUser.role
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminUser.role
     *
     * @param role the value for AdminUser.role
     *
     * @mbg.generated Sat Jul 22 10:43:34 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }
}