package com.shuodao.hrms.db.entity;

import java.util.Date;

public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.id
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.employeeid
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.contractNum
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private String contractnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.startTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.endTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.quarters
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private String quarters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contract.content
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.id
     *
     * @return the value of Contract.id
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.id
     *
     * @param id the value for Contract.id
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.employeeid
     *
     * @return the value of Contract.employeeid
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.employeeid
     *
     * @param employeeid the value for Contract.employeeid
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.contractNum
     *
     * @return the value of Contract.contractNum
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public String getContractnum() {
        return contractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.contractNum
     *
     * @param contractnum the value for Contract.contractNum
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setContractnum(String contractnum) {
        this.contractnum = contractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.startTime
     *
     * @return the value of Contract.startTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.startTime
     *
     * @param starttime the value for Contract.startTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.endTime
     *
     * @return the value of Contract.endTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.endTime
     *
     * @param endtime the value for Contract.endTime
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.quarters
     *
     * @return the value of Contract.quarters
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public String getQuarters() {
        return quarters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.quarters
     *
     * @param quarters the value for Contract.quarters
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setQuarters(String quarters) {
        this.quarters = quarters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contract.content
     *
     * @return the value of Contract.content
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contract.content
     *
     * @param content the value for Contract.content
     *
     * @mbg.generated Tue Sep 05 23:24:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}