package com.shuodao.hrms.db.entity;

import java.util.Date;

public class DemissionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DemissionInfo.id
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DemissionInfo.employeeid
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DemissionInfo.reasonsleaving
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    private String reasonsleaving;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DemissionInfo.type
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DemissionInfo.dessiontime
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    private Date dessiontime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DemissionInfo.id
     *
     * @return the value of DemissionInfo.id
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DemissionInfo.id
     *
     * @param id the value for DemissionInfo.id
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DemissionInfo.employeeid
     *
     * @return the value of DemissionInfo.employeeid
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DemissionInfo.employeeid
     *
     * @param employeeid the value for DemissionInfo.employeeid
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DemissionInfo.reasonsleaving
     *
     * @return the value of DemissionInfo.reasonsleaving
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public String getReasonsleaving() {
        return reasonsleaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DemissionInfo.reasonsleaving
     *
     * @param reasonsleaving the value for DemissionInfo.reasonsleaving
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public void setReasonsleaving(String reasonsleaving) {
        this.reasonsleaving = reasonsleaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DemissionInfo.type
     *
     * @return the value of DemissionInfo.type
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DemissionInfo.type
     *
     * @param type the value for DemissionInfo.type
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DemissionInfo.dessiontime
     *
     * @return the value of DemissionInfo.dessiontime
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public Date getDessiontime() {
        return dessiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DemissionInfo.dessiontime
     *
     * @param dessiontime the value for DemissionInfo.dessiontime
     *
     * @mbg.generated Wed Nov 01 00:11:57 CST 2017
     */
    public void setDessiontime(Date dessiontime) {
        this.dessiontime = dessiontime;
    }
}