package com.shuodao.hrms.db.entity;

public class DepartmentLevelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DepartmentLevelInfo.id
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DepartmentLevelInfo.name
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DepartmentLevelInfo.status
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DepartmentLevelInfo.id
     *
     * @return the value of DepartmentLevelInfo.id
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DepartmentLevelInfo.id
     *
     * @param id the value for DepartmentLevelInfo.id
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DepartmentLevelInfo.name
     *
     * @return the value of DepartmentLevelInfo.name
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DepartmentLevelInfo.name
     *
     * @param name the value for DepartmentLevelInfo.name
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DepartmentLevelInfo.status
     *
     * @return the value of DepartmentLevelInfo.status
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DepartmentLevelInfo.status
     *
     * @param status the value for DepartmentLevelInfo.status
     *
     * @mbg.generated Mon Sep 04 15:45:27 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}