package com.shuodao.hrms.db.entity;

public class DeptInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DeptInfo.id
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DeptInfo.dept_num
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    private String deptNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DeptInfo.dept_name
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DeptInfo.id
     *
     * @return the value of DeptInfo.id
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DeptInfo.id
     *
     * @param id the value for DeptInfo.id
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DeptInfo.dept_num
     *
     * @return the value of DeptInfo.dept_num
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public String getDeptNum() {
        return deptNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DeptInfo.dept_num
     *
     * @param deptNum the value for DeptInfo.dept_num
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public void setDeptNum(String deptNum) {
        this.deptNum = deptNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DeptInfo.dept_name
     *
     * @return the value of DeptInfo.dept_name
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DeptInfo.dept_name
     *
     * @param deptName the value for DeptInfo.dept_name
     *
     * @mbg.generated Sat Aug 19 23:28:58 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}