package com.shuodao.hrms.db.entity;

import java.util.Date;

public class Detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.id
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.department
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.job
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.workContent
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private String workcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.performance
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private String performance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.startTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.endTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Detail.employeeid
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    private String employeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.id
     *
     * @return the value of Detail.id
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.id
     *
     * @param id the value for Detail.id
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.department
     *
     * @return the value of Detail.department
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.department
     *
     * @param department the value for Detail.department
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.job
     *
     * @return the value of Detail.job
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.job
     *
     * @param job the value for Detail.job
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.workContent
     *
     * @return the value of Detail.workContent
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public String getWorkcontent() {
        return workcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.workContent
     *
     * @param workcontent the value for Detail.workContent
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setWorkcontent(String workcontent) {
        this.workcontent = workcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.performance
     *
     * @return the value of Detail.performance
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public String getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.performance
     *
     * @param performance the value for Detail.performance
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setPerformance(String performance) {
        this.performance = performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.startTime
     *
     * @return the value of Detail.startTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.startTime
     *
     * @param starttime the value for Detail.startTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.endTime
     *
     * @return the value of Detail.endTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.endTime
     *
     * @param endtime the value for Detail.endTime
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Detail.employeeid
     *
     * @return the value of Detail.employeeid
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Detail.employeeid
     *
     * @param employeeid the value for Detail.employeeid
     *
     * @mbg.generated Thu Oct 05 20:41:05 CST 2017
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
}