package com.shuodao.hrms.db.entity;

import java.util.Date;

public class Dossier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.id
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.employeeid
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.DossierNum
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private String dossiernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.context
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.remark
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.department
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.designation
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private String designation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dossier.dossiertime
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    private Date dossiertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.id
     *
     * @return the value of Dossier.id
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.id
     *
     * @param id the value for Dossier.id
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.employeeid
     *
     * @return the value of Dossier.employeeid
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.employeeid
     *
     * @param employeeid the value for Dossier.employeeid
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.DossierNum
     *
     * @return the value of Dossier.DossierNum
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public String getDossiernum() {
        return dossiernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.DossierNum
     *
     * @param dossiernum the value for Dossier.DossierNum
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setDossiernum(String dossiernum) {
        this.dossiernum = dossiernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.context
     *
     * @return the value of Dossier.context
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.context
     *
     * @param context the value for Dossier.context
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.remark
     *
     * @return the value of Dossier.remark
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.remark
     *
     * @param remark the value for Dossier.remark
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.department
     *
     * @return the value of Dossier.department
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.department
     *
     * @param department the value for Dossier.department
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.designation
     *
     * @return the value of Dossier.designation
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.designation
     *
     * @param designation the value for Dossier.designation
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dossier.dossiertime
     *
     * @return the value of Dossier.dossiertime
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public Date getDossiertime() {
        return dossiertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dossier.dossiertime
     *
     * @param dossiertime the value for Dossier.dossiertime
     *
     * @mbg.generated Thu Sep 28 23:11:02 CST 2017
     */
    public void setDossiertime(Date dossiertime) {
        this.dossiertime = dossiertime;
    }
}