package com.shuodao.hrms.db.entity;

public class employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.image
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.degree
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.rstatus
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String rstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EducationImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String educationimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.DegreeImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String degreeimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.IDcard1
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String idcard1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Education
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.IDcard2
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    private String idcard2;
    
    private String userid;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.image
     *
     * @return the value of employee.image
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.image
     *
     * @param image the value for employee.image
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position
     *
     * @return the value of employee.position
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position
     *
     * @param position the value for employee.position
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.degree
     *
     * @return the value of employee.degree
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.degree
     *
     * @param degree the value for employee.degree
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department
     *
     * @return the value of employee.department
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department
     *
     * @param department the value for employee.department
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.rstatus
     *
     * @return the value of employee.rstatus
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getRstatus() {
        return rstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.rstatus
     *
     * @param rstatus the value for employee.rstatus
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setRstatus(String rstatus) {
        this.rstatus = rstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EducationImage
     *
     * @return the value of employee.EducationImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getEducationimage() {
        return educationimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EducationImage
     *
     * @param educationimage the value for employee.EducationImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setEducationimage(String educationimage) {
        this.educationimage = educationimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.DegreeImage
     *
     * @return the value of employee.DegreeImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getDegreeimage() {
        return degreeimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.DegreeImage
     *
     * @param degreeimage the value for employee.DegreeImage
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setDegreeimage(String degreeimage) {
        this.degreeimage = degreeimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.IDcard1
     *
     * @return the value of employee.IDcard1
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getIdcard1() {
        return idcard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.IDcard1
     *
     * @param idcard1 the value for employee.IDcard1
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setIdcard1(String idcard1) {
        this.idcard1 = idcard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Education
     *
     * @return the value of employee.Education
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Education
     *
     * @param education the value for employee.Education
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.IDcard2
     *
     * @return the value of employee.IDcard2
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public String getIdcard2() {
        return idcard2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.IDcard2
     *
     * @param idcard2 the value for employee.IDcard2
     *
     * @mbg.generated Fri Aug 04 23:03:11 CST 2017
     */
    public void setIdcard2(String idcard2) {
        this.idcard2 = idcard2;
    }

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
}