package com.shuodao.hrms.db.entity;

import java.util.Date;

public class InstitutionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstitutionInfo.id
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstitutionInfo.title
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstitutionInfo.category
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstitutionInfo.content
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstitutionInfo.issuedate
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private Date issuedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstitutionInfo.id
     *
     * @return the value of InstitutionInfo.id
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    private String author;
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstitutionInfo.id
     *
     * @param id the value for InstitutionInfo.id
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstitutionInfo.title
     *
     * @return the value of InstitutionInfo.title
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstitutionInfo.title
     *
     * @param title the value for InstitutionInfo.title
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstitutionInfo.category
     *
     * @return the value of InstitutionInfo.category
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstitutionInfo.category
     *
     * @param category the value for InstitutionInfo.category
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstitutionInfo.content
     *
     * @return the value of InstitutionInfo.content
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstitutionInfo.content
     *
     * @param content the value for InstitutionInfo.content
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstitutionInfo.issuedate
     *
     * @return the value of InstitutionInfo.issuedate
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public Date getIssuedate() {
        return issuedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstitutionInfo.issuedate
     *
     * @param issuedate the value for InstitutionInfo.issuedate
     *
     * @mbg.generated Tue Aug 22 23:46:49 CST 2017
     */
    public void setIssuedate(Date issuedate) {
        this.issuedate = issuedate;
    }

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}
}