package com.shuodao.hrms.db.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.id
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.roleid
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.permission1
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String permission1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.permission2
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String permission2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.permission3
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String permission3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.permission4
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String permission4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.role_name
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.id
     *
     * @return the value of Permission.id
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.id
     *
     * @param id the value for Permission.id
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.roleid
     *
     * @return the value of Permission.roleid
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.roleid
     *
     * @param roleid the value for Permission.roleid
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.permission1
     *
     * @return the value of Permission.permission1
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getPermission1() {
        return permission1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.permission1
     *
     * @param permission1 the value for Permission.permission1
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setPermission1(String permission1) {
        this.permission1 = permission1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.permission2
     *
     * @return the value of Permission.permission2
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getPermission2() {
        return permission2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.permission2
     *
     * @param permission2 the value for Permission.permission2
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setPermission2(String permission2) {
        this.permission2 = permission2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.permission3
     *
     * @return the value of Permission.permission3
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getPermission3() {
        return permission3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.permission3
     *
     * @param permission3 the value for Permission.permission3
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setPermission3(String permission3) {
        this.permission3 = permission3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.permission4
     *
     * @return the value of Permission.permission4
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getPermission4() {
        return permission4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.permission4
     *
     * @param permission4 the value for Permission.permission4
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setPermission4(String permission4) {
        this.permission4 = permission4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Permission.role_name
     *
     * @return the value of Permission.role_name
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Permission.role_name
     *
     * @param roleName the value for Permission.role_name
     *
     * @mbg.generated Wed Sep 20 17:28:04 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}