package com.shuodao.hrms.db.entity;

import java.util.Date;

public class RewardsAndPunishments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.id
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.rewardsuser
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private String rewardsuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.rewardsTime
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private Date rewardstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.rewardsContext
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private String rewardscontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.rewardsCategory
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private String rewardscategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RewardsAndPunishments.rewardsTitle
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    private String rewardstitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.id
     *
     * @return the value of RewardsAndPunishments.id
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.id
     *
     * @param id the value for RewardsAndPunishments.id
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.rewardsuser
     *
     * @return the value of RewardsAndPunishments.rewardsuser
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public String getRewardsuser() {
        return rewardsuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.rewardsuser
     *
     * @param rewardsuser the value for RewardsAndPunishments.rewardsuser
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setRewardsuser(String rewardsuser) {
        this.rewardsuser = rewardsuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.rewardsTime
     *
     * @return the value of RewardsAndPunishments.rewardsTime
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public Date getRewardstime() {
        return rewardstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.rewardsTime
     *
     * @param rewardstime the value for RewardsAndPunishments.rewardsTime
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setRewardstime(Date rewardstime) {
        this.rewardstime = rewardstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.rewardsContext
     *
     * @return the value of RewardsAndPunishments.rewardsContext
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public String getRewardscontext() {
        return rewardscontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.rewardsContext
     *
     * @param rewardscontext the value for RewardsAndPunishments.rewardsContext
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setRewardscontext(String rewardscontext) {
        this.rewardscontext = rewardscontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.rewardsCategory
     *
     * @return the value of RewardsAndPunishments.rewardsCategory
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public String getRewardscategory() {
        return rewardscategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.rewardsCategory
     *
     * @param rewardscategory the value for RewardsAndPunishments.rewardsCategory
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setRewardscategory(String rewardscategory) {
        this.rewardscategory = rewardscategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RewardsAndPunishments.rewardsTitle
     *
     * @return the value of RewardsAndPunishments.rewardsTitle
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public String getRewardstitle() {
        return rewardstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RewardsAndPunishments.rewardsTitle
     *
     * @param rewardstitle the value for RewardsAndPunishments.rewardsTitle
     *
     * @mbg.generated Thu Oct 12 00:32:27 CST 2017
     */
    public void setRewardstitle(String rewardstitle) {
        this.rewardstitle = rewardstitle;
    }
}