package com.shuodao.hrms.db.entity;

import java.util.Date;

public class RoleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo.id
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo.roleName
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo.description
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo.createtime
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo.id
     *
     * @return the value of RoleInfo.id
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo.id
     *
     * @param id the value for RoleInfo.id
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo.roleName
     *
     * @return the value of RoleInfo.roleName
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo.roleName
     *
     * @param rolename the value for RoleInfo.roleName
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo.description
     *
     * @return the value of RoleInfo.description
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo.description
     *
     * @param description the value for RoleInfo.description
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo.createtime
     *
     * @return the value of RoleInfo.createtime
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo.createtime
     *
     * @param createtime the value for RoleInfo.createtime
     *
     * @mbg.generated Tue Sep 19 11:07:07 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}