package com.shuodao.hrms.db.entity;

import java.util.Date;

public class trainigRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.id
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.category
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String category;
    
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.nature
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.number
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.name
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.startTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.endTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.price
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.location
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.participants
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String participants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.organizer
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String organizer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.methods
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String methods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.nameOfpersonIncharge
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String nameofpersonincharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.score
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.teacher
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.classinfo
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String classinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.totalPrice
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private Integer totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.subject
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.employeeid
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainingRecord.grading
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    private String grading;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.id
     *
     * @return the value of trainingRecord.id
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.id
     *
     * @param id the value for trainingRecord.id
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.category
     *
     * @return the value of trainingRecord.category
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.category
     *
     * @param category the value for trainingRecord.category
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.nature
     *
     * @return the value of trainingRecord.nature
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.nature
     *
     * @param nature the value for trainingRecord.nature
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setNature(String nature) {
        this.nature = nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.number
     *
     * @return the value of trainingRecord.number
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.number
     *
     * @param number the value for trainingRecord.number
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.name
     *
     * @return the value of trainingRecord.name
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.name
     *
     * @param name the value for trainingRecord.name
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.startTime
     *
     * @return the value of trainingRecord.startTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.startTime
     *
     * @param starttime the value for trainingRecord.startTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.endTime
     *
     * @return the value of trainingRecord.endTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.endTime
     *
     * @param endtime the value for trainingRecord.endTime
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.price
     *
     * @return the value of trainingRecord.price
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.price
     *
     * @param price the value for trainingRecord.price
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.location
     *
     * @return the value of trainingRecord.location
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.location
     *
     * @param location the value for trainingRecord.location
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.participants
     *
     * @return the value of trainingRecord.participants
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getParticipants() {
        return participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.participants
     *
     * @param participants the value for trainingRecord.participants
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setParticipants(String participants) {
        this.participants = participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.organizer
     *
     * @return the value of trainingRecord.organizer
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getOrganizer() {
        return organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.organizer
     *
     * @param organizer the value for trainingRecord.organizer
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setOrganizer(String organizer) {
        this.organizer = organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.methods
     *
     * @return the value of trainingRecord.methods
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getMethods() {
        return methods;
    }
   
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.methods
     *
     * @param methods the value for trainingRecord.methods
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setMethods(String methods) {
        this.methods = methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.nameOfpersonIncharge
     *
     * @return the value of trainingRecord.nameOfpersonIncharge
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getNameofpersonincharge() {
        return nameofpersonincharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.nameOfpersonIncharge
     *
     * @param nameofpersonincharge the value for trainingRecord.nameOfpersonIncharge
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setNameofpersonincharge(String nameofpersonincharge) {
        this.nameofpersonincharge = nameofpersonincharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.score
     *
     * @return the value of trainingRecord.score
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.score
     *
     * @param score the value for trainingRecord.score
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.teacher
     *
     * @return the value of trainingRecord.teacher
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.teacher
     *
     * @param teacher the value for trainingRecord.teacher
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.classinfo
     *
     * @return the value of trainingRecord.classinfo
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getClassinfo() {
        return classinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.classinfo
     *
     * @param classinfo the value for trainingRecord.classinfo
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setClassinfo(String classinfo) {
        this.classinfo = classinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.totalPrice
     *
     * @return the value of trainingRecord.totalPrice
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.totalPrice
     *
     * @param totalprice the value for trainingRecord.totalPrice
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.subject
     *
     * @return the value of trainingRecord.subject
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.subject
     *
     * @param subject the value for trainingRecord.subject
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.employeeid
     *
     * @return the value of trainingRecord.employeeid
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.employeeid
     *
     * @param employeeid the value for trainingRecord.employeeid
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainingRecord.grading
     *
     * @return the value of trainingRecord.grading
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public String getGrading() {
        return grading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainingRecord.grading
     *
     * @param grading the value for trainingRecord.grading
     *
     * @mbg.generated Wed Nov 08 23:24:13 CST 2017
     */
    public void setGrading(String grading) {
        this.grading = grading;
    }
}