package com.shuodao.hrms.db.entity;

public class TrainCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TrainCategory.id
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TrainCategory.catrgorycode
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	private String catrgorycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TrainCategory.category
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	private String category;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TrainCategory.id
	 * @return  the value of TrainCategory.id
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TrainCategory.id
	 * @param id  the value for TrainCategory.id
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TrainCategory.catrgorycode
	 * @return  the value of TrainCategory.catrgorycode
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public String getCatrgorycode() {
		return catrgorycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TrainCategory.catrgorycode
	 * @param catrgorycode  the value for TrainCategory.catrgorycode
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public void setCatrgorycode(String catrgorycode) {
		this.catrgorycode = catrgorycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TrainCategory.category
	 * @return  the value of TrainCategory.category
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TrainCategory.category
	 * @param category  the value for TrainCategory.category
	 * @mbg.generated  Thu Oct 12 00:32:27 CST 2017
	 */
	public void setCategory(String category) {
		this.category = category;
	}
}