package com.shuodao.hrms.db.entity;

import java.util.Date;

public class TransferInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.id
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.employeeid
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.transfertime
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private Date transfertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.beforedept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String beforedept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.beforeposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String beforeposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.afterdept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String afterdept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.afterposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String afterposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.reason
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TransferInformation.type
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.id
     *
     * @return the value of TransferInformation.id
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.id
     *
     * @param id the value for TransferInformation.id
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.employeeid
     *
     * @return the value of TransferInformation.employeeid
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.employeeid
     *
     * @param employeeid the value for TransferInformation.employeeid
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.transfertime
     *
     * @return the value of TransferInformation.transfertime
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public Date getTransfertime() {
        return transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.transfertime
     *
     * @param transfertime the value for TransferInformation.transfertime
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setTransfertime(Date transfertime) {
        this.transfertime = transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.beforedept
     *
     * @return the value of TransferInformation.beforedept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getBeforedept() {
        return beforedept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.beforedept
     *
     * @param beforedept the value for TransferInformation.beforedept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setBeforedept(String beforedept) {
        this.beforedept = beforedept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.beforeposition
     *
     * @return the value of TransferInformation.beforeposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getBeforeposition() {
        return beforeposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.beforeposition
     *
     * @param beforeposition the value for TransferInformation.beforeposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setBeforeposition(String beforeposition) {
        this.beforeposition = beforeposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.afterdept
     *
     * @return the value of TransferInformation.afterdept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getAfterdept() {
        return afterdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.afterdept
     *
     * @param afterdept the value for TransferInformation.afterdept
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setAfterdept(String afterdept) {
        this.afterdept = afterdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.afterposition
     *
     * @return the value of TransferInformation.afterposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getAfterposition() {
        return afterposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.afterposition
     *
     * @param afterposition the value for TransferInformation.afterposition
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setAfterposition(String afterposition) {
        this.afterposition = afterposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.reason
     *
     * @return the value of TransferInformation.reason
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.reason
     *
     * @param reason the value for TransferInformation.reason
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TransferInformation.type
     *
     * @return the value of TransferInformation.type
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TransferInformation.type
     *
     * @param type the value for TransferInformation.type
     *
     * @mbg.generated Fri Oct 27 23:45:53 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}